export type FlowerByIdFlower = {
  id: string,
  namespace: string,
  flower: string,
  name: string,
  category: string,
  urls: string,
  colors: string,
  price: number,
  price100_300: number,
  price300_500: number,
  price_500: number,
  flowerPeriod: string,
  color: string,
  diametr: number,
  isHas: string,
};
